---
seed_limit: 60
data_n: 64 # 64 # number of samples per grid case
pop_n : 25 # number of agents per population class
q : 8 # quarters per simulation
r : 60 # runs per simulation. Should be factor of 60
attention_range: # [0, 0.01, 0.03, 0.06, 0.12, 0.25, 0.5, 1]
  - 0.0
  - .01
  - 0.1 # [0, 0.01, 0.03, 0.06, 0.12, 0.25, 0.5, 1]
dividend_ror_range:
  - 0.04 # [0.001, 0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1]
dividend_std_range:
  - 0.01
mock_range:
  - False
p1_range:
  - 0.05
  - 0.1
  - 0.5
  - 0.9
  - 0.95
p2_range:
  - 0.05
  - 0.1
  - 0.5
  - 0.9
  - 0.95
delta_t1_range:
  - 60
delta_t2_range:
  - 60
  
azure: false