---
seed_limit: 64 # can increase as we build out the cache
data_n: 64 # number of samples per grid case
pop_n : 25 # number of agents per population class
q : 8 # quarters per simulation
r : 60 # runs per simulation. Should be factor of 60
attention_range:
  - 0.001
  - 0.01
  - 0.1
dividend_ror_range:
  - 0.04 
dividend_std_range:
  - 0.01
mock_range:
  - False
p1_range:
  - 0.001
  - 0.01
  - 0.1
  - 0.3
  - 0.5
  - 0.7
  - 0.9
  - 0.99
  - 0.999
p2_range:
  - 0.001
  - 0.01
  - 0.1
  - 0.3
  - 0.5
  - 0.7
  - 0.9
  - 0.99
  - 0.999
delta_t1_range:
  - 60
delta_t2_range:
  - 60