---
seed_limit: 65 # can increase as we build out the cache
data_n: 256 # number of samples per grid case
pop_n : 25 # number of agents per population class
q : 8 # quarters per simulation
r : 60 # runs per simulation. Should be factor of 60
attention_range:
  - 0.00
  - 0.005
  - 0.01
  - 0.02
  - 0.04
  - 0.08
  - 0.10
  - 0.20
  - 0.40
  - 0.80
  - 1.00
dividend_ror_range:
  - 0.04
dividend_std_range:
  - 0.01
mock_range:
  - False
p1_range:
  - 0.1
p2_range:
  - 0.1
delta_t1_range:
  - 60
delta_t2_range:
  - 60
