---
attention_range: # [0, 0.01, 0.03, 0.06, 0.12, 0.25, 0.5, 1]
  - 0.05
dividend_ror_range:
  - 0.04 # [0.001, 0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1]
dividend_std_range:
  - 0.01
mock_range:
  - True # False
p1_range:
  - 0.1
  - 0.9
p2_range:
  - 0.1
  - 0.9
delta_t1_range:
  - 60
delta_t2_range:
  - 60